name: Rust CI

on: [push, pull_request, fork]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust components
        run: |
          rustup update stable
          rustup component add rustfmt clippy

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Build
        run: cargo build --all-targets
